name: Publish Alpha Release

on:
  push:
    branches:
      - development

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Get current version
      id: get_version
      run: |
        VERSION=$(python setup.py --version)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create alpha tag
      id: create_tag
      run: |
        ALPHA_VERSION="${{ env.VERSION }}-alpha.$(date +%Y%m%d%H%M%S)"
        echo "ALPHA_VERSION=$ALPHA_VERSION" >> $GITHUB_ENV
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git tag $ALPHA_VERSION
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} $ALPHA_VERSION

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*

    - name: Create GitHub release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.ALPHA_VERSION }}
        release_name: Alpha Release ${{ env.ALPHA_VERSION }}
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}