name: Auto Tag on Development Branch

on:
  push:
    branches:
      - development

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the current version
        id: get_version
        run: |
          ALPHA_VERSION="0.0.5a0-alpha.$(date +%Y%m%d%H%M%S)"
          echo "ALPHA_VERSION=$ALPHA_VERSION" >> $GITHUB_ENV

      - name: Delete existing local tag (if any)
        run: |
          git tag -d ${{ env.ALPHA_VERSION }} || true

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git tag ${{ env.ALPHA_VERSION }}
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} ${{ env.ALPHA_VERSION }}
