name: Auto Tag on Development Branch

on:
  push:
    branches:
      - development

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the current version
        id: get_version
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Delete existing local tag (if any)
        run: |
          git tag -d ${{ env.VERSION }} || true

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
